version: '3.8'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-create_tables.sql:ro

  chatbot:
    build:
      context: ./
      target: development
    depends_on:
      - db
    environment:
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASE_URL: "${DATABASE_URL}"
      TROLLABOT_TOKEN: "${TROLLABOT_TOKEN}"
