version: '3.8'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: "trollabot"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-create_tables.sql:ro

  chatbot:
    build:
      context: ./
      target: development
    depends_on:
      - db
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/trollabot?user=postgres&password=password"
      TROLLABOT_TOKEN: "${TROLLABOT_TOKEN}"
    ports:
      - '8080:8080'