version: '3.8'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-create_tables.sql:ro

  chatbot:
    build:
      context: ./
      target: development
    depends_on:
      - db
    environment:
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASE_URL: "jdbc:postgresql://ec2-3-225-79-57.compute-1.amazonaws.com:5432/d32um56ap42olc?user=rjmayszlhyzpov&password=15a1c07b77224867afdb7464ff0d5f5b7b4842162443d533b89d3c44cd597075"
      TROLLABOT_TOKEN: "${TROLLABOT_TOKEN}"
